import { StyleSheet } from 'react-native';

module.exports = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF',
    padding: 10,
  },
  imgContainer: {
    paddingTop: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleText: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Montserrat-SemiBold',
    color: 'rgb(76,76,76)',
    paddingTop: 15,
  },
  errorTextContainer: {
    justifyContent: 'center',
    marginTop: 20,
    marginHorizontal: 10,
    backgroundColor: '#ed7f7e',
    borderRadius: 4,
    height: 30,
  },
  errorText: {
    padding: 5,
    fontSize: 14,
    borderRadius: 4,
    overflow: 'hidden',
    fontFamily: 'Montserrat-Light',
    color: 'rgb(255,255,255)',
  },
  inputStyle: {
    marginTop: 20,
    height: 40,
    borderColor: '#d7d7d7',
    borderWidth: 1,
    fontSize: 14,
    borderRadius: 2,
    marginHorizontal: 10,
    paddingHorizontal: 10,
  },
  errorBorder: {
    borderColor: '#ed7f7e',
  },
  loginText: {
    fontSize: 14,
    color: 'rgb(255,255,255)',
    fontFamily: 'Montserrat-Regular',
    textAlign: 'center',
  },
  bottomButtonsView: {
    height: 90,
    marginHorizontal: 5,
    marginTop: 20,
  },
  loginBtnStyle: {
    backgroundColor: '#83bdef',
    borderRadius: 4,
    height: 40,
    marginHorizontal: 5,
    marginTop: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  frtPassBtn: {
    borderRadius: 4,
    height: 40,
    marginHorizontal: 10,
    marginTop: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  frtPassText: {
    fontSize: 14,
    color: 'rgb(128,128,128)',
    fontFamily: 'Montserrat-Regular',
    textAlign: 'center',
  },
  tabletElivationView: {
    height: 400,
    width: 320,
    elevation: 10,
  },
  shadowStyle: {
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#ddd',
    borderBottomWidth: 0,
    shadowColor: 'black',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 30,
    elevation: 1,
    marginLeft: 5,
    marginRight: 5,
    marginTop: 10,
  },
  keyboardContainer: {
    flex: 1,
  },
  alertBlock: {
    flex: 1,
    marginHorizontal: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
    borderWidth: 1,
    backgroundColor: '#ed7f7e',
    borderColor: '#ed7f7e',
    justifyContent: 'center',
    marginTop: 10,
  },
  successBlock: {
    flex: 1,
    marginHorizontal: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 4,
    borderWidth: 1,
    backgroundColor: 'green',
    borderColor: 'green',
    justifyContent: 'center',
    marginTop: 10,
  },
  alertText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Montserrat-Light',
  },
});
